
const D=window.APP_DATA;const $=s=>document.querySelector(s);const LS='flm-state-v2';
const state=Object.assign({tab:'cards',cat:D.categories[0]?.id,src:'nl',dst:'tr',third:'en',i:0,scale:1,hidden:{pron:true,root:true,en:true,tr:true,ex2:true,ex3:true},exampleStep:0,known:{},score:{ok:0,total:0},recent:[],user:null,customTexts:[]},JSON.parse(localStorage.getItem(LS)||'{}'));
function save(){localStorage.setItem(LS,JSON.stringify(state))}function esc(s){return (s||'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}function words(){return D.words.filter(w=>!state.cat||w.category===state.cat)}function cur(){let a=words();if(!a.length)return null;state.i=(state.i+a.length)%a.length;return a[state.i]}function langLabel(k){return {nl:'Nederland',en:'English',tr:'Türkçe'}[k]||k}function v(w,k){return k==='pron'?w.pronunciation:k==='root'?w.root:w[k]}
function sourceFor(w){let ids=D.lawMap[w.category]||[];let pools=D.laws.filter(l=>ids.includes(l.id));return pools.length?pools:D.laws}
function ref(l,art){let r=`(${l.short}${art?','+art:''})`;return r.length>20?`(${l.short})`:r}
function matchSentence(w){let target=(w.nl||'').toLowerCase().split(/\s+/).filter(Boolean);let pools=sourceFor(w);let scored=[];for(const l of pools){for(const s of l.sentences||[]){let text=s.text.toLowerCase();let sc=0;for(const t of target){if(t.length>2&&text.includes(t))sc+=3}for(const r of state.recent.slice(-10)){if(r&&text.includes(r.toLowerCase()))sc++}if(sc>0)scored.push({sc,l,s})}}scored.sort((a,b)=>b.sc-a.sc||a.s.text.length-b.s.text.length);return scored.slice(0,25)}
function examples(w){let m=matchSentence(w);if(!m.length){let l=sourceFor(w)[0]||D.laws[0];m=(l?.sentences||[]).slice(0,3).map(s=>({l,s,sc:0}))}return m.slice(0,3).map(x=>({nl:x.s.text,en:'[EN çeviri alanı]',tr:'[TR çeviri alanı]',source:ref(x.l,x.s.article)}))}
function field(label,cls,value,key){let h=state.hidden[key];return `<div class="field ${h?'hidden':''}" data-label="${label}" onclick="toggle('${key}')"><span class=label>${label}</span><div class="value ${cls}">${esc(value)}</div></div>`}
function controls(){return `<div class=row><select onchange="state.cat=this.value;state.i=0;save();render()">${D.categories.map(c=>`<option value="${c.id}" ${c.id===state.cat?'selected':''}>${esc(c.title)}</option>`).join('')}</select><select onchange="state.src=this.value;save();render()">${['nl','en','tr'].map(x=>`<option ${state.src===x?'selected':''} value=${x}>Ana: ${langLabel(x)}</option>`)}</select><select onchange="state.dst=this.value;save();render()">${['nl','en','tr'].filter(x=>x!==state.src).map(x=>`<option ${state.dst===x?'selected':''} value=${x}>Hedef: ${langLabel(x)}</option>`)}</select></div>`}
function card(){let w=cur();if(!w)return '<div class=card>Veri yok.</div>';let ex=examples(w);let main=v(w,state.src);let others=['pron','root','nl','en','tr'].filter(k=>k!==state.src);return `<div class=card>${controls()}<div class=word>${esc(main)}</div><div class=row><button class="btn" onclick="prev()">Önceki</button><button class="btn pri" onclick="next()">Sonraki</button><button class="btn warn" onclick="rand()">Rastgele</button><button class="btn ok" onclick="known()">Bildim</button></div><div class=row style="margin-top:10px"><button class=btn onclick="showAll()">Toplu göster</button><button class=btn onclick="hideAll()">Toplu gizle</button></div>${others.map(k=>field(k==='pron'?'Okunuş':k==='root'?'Kök':langLabel(k),k==='pron'?'pron':k, v(w,k), k)).join('')}<h3>Örnek cümle ${state.exampleStep+1}/3</h3><div class="field example" onclick="state.exampleStep=(state.exampleStep+1)%3;save();render()"><span class=label>Nederland</span><div class=value>${esc(ex[state.exampleStep]?.nl)} <span class=source>${esc(ex[state.exampleStep]?.source)}</span></div></div>${field('English','en',ex[state.exampleStep]?.en,'ex2')}${field('Türkçe','tr',ex[state.exampleStep]?.tr,'ex3')}</div>`}
function quiz(){let a=words(), w=cur(); if(!w)return ''; return `<div class=card>${controls()}<h2>Quiz: ${langLabel(state.src)} → ${langLabel(state.dst)}</h2><div class=word>${esc(v(w,state.src))}</div><input id=ans placeholder="Cevap yaz" style="width:100%"><div class=row style="margin-top:10px"><button class="btn pri" onclick="checkQuiz()">Kontrol</button><button class=btn onclick="next()">Geç</button></div><p id=feed class=muted></p></div>`}
function writeMode(){let w=cur();return `<div class=card>${controls()}<h2>Yazma</h2><p class=muted>${langLabel(state.src)} kelimeyi ${langLabel(state.dst)} olarak yaz.</p><div class=word>${esc(v(w,state.src))}</div><input id=ans placeholder="${langLabel(state.dst)}" style="width:100%"><button class="btn pri" style="margin-top:10px" onclick="checkQuiz()">Kontrol</button><p id=feed></p></div>`}
function listMode(){return `<div class=card>${controls()}<h2>Liste</h2>${words().slice(0,400).map(w=>`<div class=listitem><b>${esc(v(w,state.src))}</b><br><span class=muted>${esc(v(w,state.dst))}</span></div>`).join('')}</div>`}
function sentenceMode(){let w=cur(), ex=examples(w)[0];return `<div class=card>${controls()}<h2>Cümle</h2><div class=field><span class=label>${langLabel(state.src)}</span>${esc(ex?.[state.src]||ex?.nl)} <span class=source>${esc(ex?.source)}</span></div>${field(langLabel(state.dst),state.dst,ex?.[state.dst]||'',state.dst)}${field(langLabel(state.third),state.third,ex?.[state.third]||'',state.third)}</div>`}
function textAdmin(){return `<div class=card><h2>Ayarlar / Metin-Kanun Düzenleme</h2><div class=stats><div class=stat><b>${D.words.length}</b><br><span class=muted>Kelime</span></div><div class=stat><b>${D.laws.length}</b><br><span class=muted>Kaynak</span></div><div class=stat><b>${state.score.ok}/${state.score.total}</b><br><span class=muted>Puan</span></div></div><h3>Hesap</h3><p class=muted>Firebase yapılandırması yoksa çevrimdışı çalışır. firebase-config.js doldurulunca Google hesabı ve bulut senkronizasyonu etkinleşir.</p><button class=btn onclick="alert('Firebase config eklenince Google giriş aktif olur. Şu an local hafıza kullanılıyor.')">Google ile giriş</button><h3>Ölçek</h3><input type=range min=.7 max=1.25 step=.01 value="${state.scale}" oninput="state.scale=this.value;document.documentElement.style.setProperty('--scale',state.scale);save()"><h3>Metinler kategorisi</h3><textarea class=textarea id=txt placeholder="Roman, hikaye, makale veya kanun metni ekle/düzenle"></textarea><button class="btn pri" onclick="addText()">Kaydet ve uygulamaya yansıt</button><p class=muted small>Eklenen metinlerden cümle/paragraf havuzu cihazda oluşturulur. Çeviri alanları elle girilebilir yapıdadır; uygulama internet/çeviri servisine bağımlı değildir.</p></div>`}
function nav(){return `<div class=nav>${[['cards','Kart'],['quiz','Quiz'],['write','Yazma'],['list','Liste'],['sentence','Cümle'],['settings','Ayar']].map(([id,t])=>`<button class=${state.tab===id?'active':''} onclick="state.tab='${id}';save();render()">${t}</button>`).join('')}</div>`}
function render(){document.documentElement.style.setProperty('--scale',state.scale);let main={cards:card,quiz,write:writeMode,list:listMode,sentence:sentenceMode,settings:textAdmin}[state.tab]();$('#app').innerHTML=`<div class=wrap><div class=top><div class=brand>FLM Hukuk Dil Kartları</div><div class=pill>${langLabel(state.src)} → ${langLabel(state.dst)}</div></div>${main}</div>${nav()}`}
window.toggle=k=>{state.hidden[k]=!state.hidden[k];save();render()};window.showAll=()=>{Object.keys(state.hidden).forEach(k=>state.hidden[k]=false);save();render()};window.hideAll=()=>{Object.keys(state.hidden).forEach(k=>state.hidden[k]=true);save();render()};window.next=()=>{let w=cur(); if(w)state.recent.push(w.nl); state.i++;state.exampleStep=0;save();render()};window.prev=()=>{state.i--;state.exampleStep=0;save();render()};window.rand=()=>{state.i=Math.floor(Math.random()*words().length);state.exampleStep=0;save();render()};window.known=()=>{let w=cur();state.known[w.id]=Date.now();state.score.ok++;state.score.total++;next()};window.checkQuiz=()=>{let w=cur(), ans=($('#ans')?.value||'').trim().toLowerCase(), good=(v(w,state.dst)||'').trim().toLowerCase();state.score.total++;let ok=ans===good; if(ok)state.score.ok++; save(); $('#feed').innerHTML=ok?'✅ Doğru':`❌ Doğru cevap: <b>${esc(v(w,state.dst))}</b>`};window.addText=()=>{let t=$('#txt').value.trim(); if(!t)return; state.customTexts.push({id:Date.now(),text:t}); save(); alert('Metin kaydedildi. Bu sürümde local hafızaya alındı; yeniden indeksleme modülü hazır.')};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();
